### ISSUE TITLE
Log when a circuit breaker will be replaced

### ISSUE THREAD

**Issue by jbellmann** [MALPI/failsafe-actuator#1]
You can log [here](https://github.com/MALPI/failsafe-actuator/blob/master/src/main/java/de/coderebell/failsafeactuator/CircuitBreakerRegistry.java#L36) when return value is not null.

Or, maybe better, make this configurable via ConfigurationProperty-Object to fail if circuit breaker will be replaced.

Would you accept PR's for that?

**Comment by MALPI** [comment]
I also thought about to throw an exception if the breaker is getting replaced. 

Actually, I don't understand why to log when a breaker is added?

**Comment by jbellmann** [comment]
> There is no check which avoids overwriting of identifiers.

Just to make people aware of that it happens (overwriting an existing circuit breaker). Throwing exception is also fine.

**Comment by MALPI** [comment]
Yeah, I only mentioned that in the javadoc. A PR is welcome.

**Comment by MALPI** [comment]
Merged
