### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by jbellmann** [MALPI/failsafe-actuator#2]
When I try to build the project after cloning, I go the following :

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRepackage'.
> Unable to find main class

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
```

PR will come.

**Comment by MALPI** [comment]
I actually didn't provide a buildscript so far... basically It fails because it's not a spring boot project which you can run...

Thanks for input.

**Comment by MALPI** [comment]
I just removed the spring boot plugin from the build, since it shouldn't be there actually.
